_target_: grinch.DataLoader.Config

data_path: 'data/ZeiselBrainData.h5ad'
write_path: 'data/ZeiselBrainData_prepd.h5ad'

worker:
  _target_: grinch.GRPipeline.Config
  processors:
    - _target_: grinch.FilterCells.Config
      min_counts: 50
    - _target_: grinch.FilterGenes.Config
      min_counts: 10
    - _target_: grinch.NormalizeTotal.Config
      total_counts: 100000
    - _target_: grinch.Log1P.Config
    - _target_: grinch.PCA.Config
      n_components: 50
    - _target_: grinch.UMAP.Config
      x_key: obsm.x_pca
    - _target_: grinch.KMeans.Config
    - _target_: grinch.TTest.Config
      group_key: obs.kmeans
      is_logged: true
    - _target_: grinch.GSEA.Config
